apiVersion: apps/v1
kind: Deployment
metadata:
  name: rules-service
  namespace: nao-enche-business
  labels:
    app: rules-service
    component: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rules-service
  template:
    metadata:
      labels:
        app: rules-service
        component: microservice
    spec:
      containers:
      - name: rules-service
        image: nao-enche/rules-service:latest
        ports:
        - containerPort: 3008
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3008"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: rules-service-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: rules-service-secrets
              key: jwt-secret
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: rules-service-config
              key: cors_origin
        - name: RATE_LIMIT_WINDOW_MS
          valueFrom:
            configMapKeyRef:
              name: rules-service-config
              key: rate_limit_window_ms
        - name: RATE_LIMIT_MAX
          valueFrom:
            configMapKeyRef:
              name: rules-service-config
              key: rate_limit_max
        - name: ENABLE_METRICS
          valueFrom:
            configMapKeyRef:
              name: rules-service-config
              key: enable_metrics
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3008
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3008
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
